### PR TITLE
Trivial analyzer + script to add energy matrix

### PR DESCRIPTION
**Pull request by bainbrid**

### CODE REVIEW

**Comment by mverzett** [comment]
* Are all of these changes or it needs rebase or something?
  * curiosity: what is LowPtGsfElectronsAnalyzer?

**Comment by bainbrid** [comment]
These are all the changes. Why do you ask? (I did say it wasn’t much. I’ve basically thrown away a bunch of stuff that’s probably obsolete now.) 

It’s a trivial analyser that I use to check outputs. It just prints the various collection sizes.

**Comment by mverzett** [comment]
> These are all the changes. Why do you ask? (I did say it wasn’t much. I’ve basically thrown away a bunch of stuff that’s probably obsolete now.)

I saw some of my commits in the list, that made me doubt that something went wrong

**Comment by bainbrid** [comment]
Is that because some of my (irrelevant) commits are very old and so yours are interspersed between mine when ordered by commit date?

**Comment by bainbrid** [comment]
I can try rebase ... not sure what will happen.

**Comment by mverzett** [comment]
OK, no need then, I will merge and hope for the best

**Pull request merged**
