### PR TITLE
Latest ntuplizer code (2019Jul22)

### PR DESCRIPTION
**Pull request by bainbrid**
@mverzett don't feel you have to merge - it's hacky - I can tidy up when I get back.

### CODE REVIEW

**Comment by bainbrid** [comment]
This is updated to include the new Ntuplizer code: IDNtuplizer.
(IDFeatures will be deprecated.)

**Comment by bainbrid** [comment]
@mverzett please consider merging this - it will give you the latest version of the ntuples.
See README.md

**Comment by bainbrid** [comment]
hi @mverzett do you plan to merge? any concerns?

**Comment by mverzett** [comment]
@bainbrid , no, just trying to get the nano up and running before focusing on this :)

**Comment by mverzett** [comment]
I did not check completely, but looks OK

**Pull request merged**
